export default ActionTypes = {
  CHANGE_FIELD: 'CHANGE_FIELD',
  SAVE_PLAYER_ID: 'SAVE_PLAYER_ID',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_STARTED: 'LOGIN_STARTED',
};
